trigger:
- deploy

resources:
  containers:
  - container: builder
    image: locawebci/ea-op-ful-cloud-ruby-test:3.0.3-latest
    endpoint: docker-registry

stages:
- stage: Deployment
  displayName: "Deployment"
  jobs:
  - job: Deploy
    pool: LW.Private.Agents
    displayName: 'Push Gem to Locaweb Gems'
    container: builder
    steps:
      - script: bundle install --retry=3 --jobs=8
        displayName: 'Bundle install'
        target:
          container: builder

      - script: |
          gem sources -a http://gems.locaweb.com.br/
          ( ( gem list | grep geminabox ) || gem install geminabox --source https://gems.locaweb.com.br --no-document )
          bundle exec rake build
          bundle exec rake publish
        displayName: 'Gem Publish'
        target:
          container: builder